title: Game development
author: Shinomiya
email: waifu@hoho.com
description: > # this means to ignore newlines until "baseurl:"
  It's a good site to start a whole new project. It contains a thoroughly full guide for you to understand the creating game project and make your first debut.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
